name: Register
on:
  push:
    tags:
      - 'v*'
jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
